spring:
  jpa:
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
  data:
    rest:
      default-page-size: 18
  main:
    allow-bean-definition-overriding: true
  security:
    filter:
      order: 10
  thymeleaf:
    enable-spring-el-compiler: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    protocol: smtp
    properties:
      mail:
        debug: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
debug: true

